type=hadoopJava
job.class=org.apache.hadoop.examples.RandomTextWriter
classpath=/etc/hadoop/conf:/usr/lib/hadoop/lib/*:/usr/lib/hadoop/.//*:/usr/lib/hadoop-hdfs/./:/usr/lib/hadoop-hdfs/lib/*:/usr/lib/hadoop-hdfs/.//*:/usr/lib/hadoop-yarn/lib/*:/usr/lib/hadoop-yarn/.//*:/usr/lib/hadoop-mapreduce/lib/*:/usr/lib/hadoop-mapreduce/.//*
hadoop-inject.mapreduce.randomtextwriter.totalbytes=104857600
hadoop-ingest.mapreduce.randomtextwriter.bytespermap=104857600
main.args=random-words
dependencies=clean-words
